// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BackupStartupItems():Promise<boolean>;

export function FetchStartupItems():Promise<Array<main.StartupEntry>>;

export function PrepareCacheDirectory():Promise<void>;

export function ShowExecutableLocation(arg1:string):Promise<void>;
