// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupStartupItems() {
  return window['go']['main']['App']['BackupStartupItems']();
}

export function FetchStartupItems() {
  return window['go']['main']['App']['FetchStartupItems']();
}

export function ShowExecutableLocation(arg1) {
  return window['go']['main']['App']['ShowExecutableLocation'](arg1);
}
