// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BackupStartupItem(arg1:number):Promise<void>;

export function BackupStartupItems():Promise<boolean>;

export function FetchStartupItems(arg1:boolean):Promise<Array<main.StartupEntry>>;

export function PrepareCacheDirectory():Promise<void>;

export function RemoveRegistryEntry(arg1:number):Promise<boolean>;

export function ShowExecutableLocation(arg1:string):Promise<void>;
