// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupStartupItem(arg1) {
  return window['go']['main']['App']['BackupStartupItem'](arg1);
}

export function BackupStartupItems() {
  return window['go']['main']['App']['BackupStartupItems']();
}

export function FetchStartupItems(arg1) {
  return window['go']['main']['App']['FetchStartupItems'](arg1);
}

export function PrepareCacheDirectory() {
  return window['go']['main']['App']['PrepareCacheDirectory']();
}

export function RemoveRegistryEntry(arg1) {
  return window['go']['main']['App']['RemoveRegistryEntry'](arg1);
}

export function ShowExecutableLocation(arg1) {
  return window['go']['main']['App']['ShowExecutableLocation'](arg1);
}
